-- CREATE USER GENESIS_USER IDENTIFIED BY localPassword1;
-- CREATE SCHEMA GENESIS AUTHORIZATION genesis_user IDENTIFIED BY localPassword1;

CREATE TABLE SPECIE
(
    ID            LONG     PRIMARY KEY,
    NAME          VARCHAR(50) NOT NULL,
    RNA_LENGTH    INT         NOT NULL,
    MAX_CHILDREN  INT         NOT NULL,
    MAX_MUTATIONS INT         NOT NULL,
    MAX_AGE       INT,

    CONSTRAINT SPECIE_NAME_UNIQUE UNIQUE (NAME)
);
GRANT SELECT, INSERT, UPDATE, DELETE on SPECIE to sa;
CREATE SEQUENCE SPECIE_SEQ start with 10 INCREMENT BY 1;

CREATE TABLE CREATURE
(
    ID              LONG       PRIMARY KEY,
    PARENT_ID       LONG          NOT NULL,
    NAME            VARCHAR(50),
    RNA             VARCHAR(4000) NOT NULL,
    AGE             INT           NOT NULL DEFAULT 0,
    SPECIE_ID       LONG          NOT NULL,
    STATUS          VARCHAR(50)   NOT NULL,
    SCORE           INT,

    CONSTRAINT CREATURE_SPECIES_FK FOREIGN KEY (SPECIE_ID) REFERENCES SPECIE(ID)
);
GRANT SELECT, INSERT, UPDATE, DELETE on CREATURE to sa;
CREATE SEQUENCE CREATURE_SEQ start with 1 INCREMENT BY 1;

